name: scmli
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::python=3
  - conda-forge::biopython
  - conda-forge::pandas
  - lxml
  - fastqc
  - trim-galore>=0.6.0
  - flake8
  - pytest
  - r-ggplot2
  - snpEff=5.0
  - snippy=4.6
  - bioconda::tabixpp=1.1.0
  - bcftools
