# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.9
        channels: bioconda,conda-forge,defaults
        channel-priority: true
        activate-environment: test
    - name: Install dependencies
      run: |
        #conda info
        #conda list
        conda install -n test pandas biopython lxml fastqc trim-galore>=0.6.0 flake8 pytest r-base r-ggplot2 snippy bcftools
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Lint with flake8
      shell: bash -l {0}
      run: |
        cd ${{ github.workspace }}
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        cd ${{ github.workspace }}/test
        pytest
